# Generated by Django 4.0.3 on 2022-04-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options_user_email_user_py_user_realname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品类别ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='商品类别名')),
                ('specifications', models.TextField(verbose_name='商品类别描述，JSON格式')),
            ],
            options={
                'verbose_name': '商品分类一覧表',
                'verbose_name_plural': '商品分类一覧表',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('prod_desc', models.TextField(verbose_name='商品描述')),
                ('prod_price', models.FloatField(verbose_name='商品原价')),
                ('prod_now_price', models.FloatField(verbose_name='商品现价')),
                ('prod_pic1', models.URLField(verbose_name='商品图片1')),
                ('prod_pic2', models.URLField(verbose_name='商品图片2')),
                ('prod_pic3', models.URLField(verbose_name='商品图片3')),
                ('prod_pic4', models.URLField(verbose_name='商品图片4')),
                ('prod_pic5', models.URLField(verbose_name='商品图片5')),
                ('prod_addtime', models.DateTimeField(auto_now_add=True, verbose_name='商品新增时间')),
                ('prod_modtime', models.DateTimeField(auto_now=True, verbose_name='商品最后修改时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.category')),
            ],
            options={
                'verbose_name': '商品详情一覧表',
                'verbose_name_plural': '商品详情一覧表',
                'db_table': 'product',
            },
        ),
    ]
