# Generated by Django 4.0.3 on 2022-04-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='category',
            name='specifications',
            field=models.TextField(verbose_name='商品类别规格，JSON格式'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic1',
            field=models.FileField(upload_to='product', verbose_name='商品图片1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic2',
            field=models.FileField(upload_to='product', verbose_name='商品图片2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic3',
            field=models.FileField(upload_to='product', verbose_name='商品图片3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic4',
            field=models.FileField(upload_to='product', verbose_name='商品图片4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic5',
            field=models.FileField(upload_to='product', verbose_name='商品图片5'),
        ),
    ]
