# Generated by Django 4.0.3 on 2022-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_product_prod_num_alter_category_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_pic1',
            field=models.TextField(verbose_name='商品图片1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic2',
            field=models.TextField(verbose_name='商品图片2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic3',
            field=models.TextField(verbose_name='商品图片3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic4',
            field=models.TextField(verbose_name='商品图片4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_pic5',
            field=models.TextField(verbose_name='商品图片5'),
        ),
    ]
