# Generated by Django 4.0.4 on 2022-05-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_product_prod_pic1_alter_product_prod_pic2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='ユーザ名')),
                ('birth_day', models.DateField(verbose_name='生年月日')),
                ('age', models.PositiveSmallIntegerField(null=True, verbose_name='年齢')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
